### ISSUE TITLE
Find ?

### ISSUE THREAD

**Issue by arnouxor** [maltyxx/origami#3]
I cannot do that :

        $model_r = new \Entity\gmb\right();
        $rights = $model_r->find();

I have the following error : 
Origami a rencontré un problème : L'association 'find' est introuvable dans le modèle Entity\gmb\right

**Comment by maltyxx** [comment]
$rights = \Entity\gmb\right::find();

**Comment by maltyxx** [comment]
$rights = \Entity\gmb\right::where('id', 1)->find();
