### ISSUE TITLE
FATAL ERROR incomprehensible

### ISSUE THREAD

**Issue by gaudiauj** [maltyxx/origami#6]
Bonjour,

je remarque une grosse erreur sur Origami lorsque je souhaite l'utiliser de la manière suivante (préparer un select et faire le find par la suite): 

if (isset($filter['project_current'])) {
 \Entity\versus\project::where('project.enumprojectstate_id',1);
}

$results = Entity\versus\project::find();

**Comment by maltyxx** [comment]
if (isset($filter['project_current'])) {
    $query = \Entity\versus\project::where('project.enumprojectstate_id',1);
}

$results = $query->find();
