### ISSUE TITLE
Autoincrement

### ISSUE THREAD

**Issue by 4k1r0** [maltyxx/origami#9]
Origami ne gère pas les clés primaires qui ne sont pas en auto-increment.
Si on tente de definir la clé primaire manuellement il detecte que c'est une requete de type update et non insert

**Comment by 4k1r0** [comment]
D'apres la maniere dont est fait le find_one() il devrait s'appeler find_first() - dommage qu'Origami boucle sur tous les resutlat avant de retourner le premier dans le cas d'un find_one()

**Comment by maltyxx** [comment]
Oui effectivement le champ id doit être obligatoirement en auto-increment.

**Comment by maltyxx** [comment]
Non heureusement ça ne fonctionne pas comme ça, il y a un "limit 1 » en SQL envoyé dans la requête lorsqu’on fait appel a la méthode fine_one();
